### ISSUE TITLE
Automatizar la publicación de un release

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#43]
**Prioridad:** alta

**Descripción**
Automatizar a través de Travis CI el proceso de publicación de una release en GitHub: fichero comprimido que contiene el plugin, versión y changelog.

Más información: https://docs.travis-ci.com/user/deployment/releases/

**Comment by juahueceb1** [comment]
Se ha conseguido automatizar la publicación de un release en GitHub a través de Travis CI. Para ello, se ha añadido el siguiente código dentro del fichero de configuración _.travis.yml_.

```
-provider: releases
 api_key:
   secure: <TOKEN>
 skip_cleanup: true
 name: <Título de la release>
 body: <Changelog>
 draft: false
 on:
  repo: EGC-G2-Trabajo-1718/RedesSociales
  tags: true
  branch: master
```
